// flow-typed signature: ef657c55d0991842422270d0f1d51418
// flow-typed version: <<STUB>>/react-scripts_v1.1.4/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scripts' {
  declare module.exports: any;
}
